--creating User table;
CREATE TABLE IF NOT EXISTS USERS
     (ID INTEGER PRIMARY KEY  AUTOINCREMENT   NOT NULL,
     NAME          TEXT    NOT NULL,
     DOB          DATETIME    NOT NULL,
     MOBILE          TEXT    NOT NULL,
     EMAIL          TEXT    NOT NULL,
     GENDER          TEXT    NOT NULL);

--creating country table;
CREATE TABLE IF NOT EXISTS COUNTRY
     (ID INTEGER PRIMARY KEY  AUTOINCREMENT   NOT NULL,
     CODE           TEXT    NOT NULL,
     TITLE          TEXT     NOT NULL);


--creating State table;
CREATE TABLE IF NOT EXISTS STATE
     (ID INTEGER PRIMARY KEY  AUTOINCREMENT   NOT NULL,
     CODE           TEXT    NOT NULL,
     TITLE          TEXT     NOT NULL,
     COUNTRY_ID     INTEGER     NOT NULL,
     FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (id));


--creating City table;
CREATE TABLE IF NOT EXISTS CITY
     (ID INTEGER PRIMARY KEY  AUTOINCREMENT   NOT NULL,
     CODE          TEXT     NOT NULL,
     TITLE   TEXT     NOT NULL,
     STATE_ID     INTEGER     NOT NULL,
     FOREIGN KEY (STATE_ID) REFERENCES STATE(id));


--creating Address table;
CREATE TABLE IF NOT EXISTS ADDRESS
     (ID INTEGER PRIMARY KEY  AUTOINCREMENT   NOT NULL,
     PIN_CODE          INTEGER     NOT NULL,
     STREET_NO       TEXT     NOT NULL,
     LANDMARK       TEXT     NOT NULL,
     CITY_ID     INTEGER     NOT NULL,
     FOREIGN KEY (CITY_ID) REFERENCES CITY(id));


--creating Theater table;
CREATE TABLE IF NOT EXISTS THEATER
     (ID INTEGER PRIMARY KEY  AUTOINCREMENT   NOT NULL,
     CODE          TEXT     NOT NULL,
     TITLE   TEXT     NOT NULL,
     ADDRESS_ID     INTEGER     NOT NULL,
     FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(id));

--creating Theater Seating Arrangements table;
CREATE TABLE IF NOT EXISTS THEATER_SEATING_ARRANGEMENTS
     (ID INTEGER PRIMARY KEY  AUTOINCREMENT   NOT NULL,
     SEAT_CLASS     TEXT     NOT NULL,
     SEAT_LABEL     TEXT     NOT NULL,
     THEATER_ID     INTEGER     NOT NULL,
     FOREIGN KEY (THEATER_ID) REFERENCES THEATER(id)
     );

--creating Movie table;
CREATE TABLE IF NOT EXISTS MOVIE
     (ID INTEGER PRIMARY KEY  AUTOINCREMENT   NOT NULL,
     TITLE          TEXT    NOT NULL,
     MOVIE_TYPE          TEXT    NOT NULL,
     GENRE          TEXT    NOT NULL);


--creating Movie Theater table;
CREATE TABLE IF NOT EXISTS THEATER_MOVIE
     (ID INTEGER PRIMARY KEY  AUTOINCREMENT   NOT NULL,
     MOVIE_ID     INTEGER     NOT NULL,
     THEATER_ID     INTEGER     NOT NULL,
     TICKET_PRICE     INTEGER     NOT NULL,
     MOVIE_STATUS      TEXT    NOT NULL,
     MOVIE_TIME        DATETIME NOT NULL,
     FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(id),
     FOREIGN KEY (THEATER_ID) REFERENCES THEATER(id));


--creating Movie Booking table;
CREATE TABLE IF NOT EXISTS MOVIE_BOOKING
     (ID INTEGER PRIMARY KEY  AUTOINCREMENT   NOT NULL,
     USER_ID     INTEGER     NOT NULL,
     THEATER_MOVIE_ID     INTEGER     NOT NULL,
     THEATER_SEATING_ARRANGEMENTS_ID  INTEGER  NOT NULL,
     BOOKING_STATUS INTEGER NOT NULL,
     FOREIGN KEY (USER_ID) REFERENCES USERS(id),
     FOREIGN KEY (THEATER_MOVIE_ID) REFERENCES THEATER_MOVIE(id),
     FOREIGN KEY (THEATER_SEATING_ARRANGEMENTS_ID) REFERENCES THEATER_SEATING_ARRANGEMENTS(id)
     );



